name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libglfw3-dev libglew-dev libimgui-dev libgtest-dev

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: minesweeper-linux
        path: build/Minesweeper
        retention-days: 7

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'  # Latest stable version

    - name: Install dependencies with vcpkg
      run: |
        vcpkg install glfw3:x64-windows
        vcpkg install glew:x64-windows
        vcpkg install imgui[glfw-binding,opengl3-binding]:x64-windows
        vcpkg install gtest:x64-windows

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Run tests
      run: |
        cd build
        ctest -C Release --output-on-failure

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: minesweeper-windows
        path: build/Release/Minesweeper.exe
        retention-days: 7

  build-macos:
    name: Build on macOS
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install cmake glfw glew googletest
        # ImGui needs to be installed manually or via vcpkg
        brew install pkg-config

    - name: Setup vcpkg for ImGui
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'

    - name: Install ImGui with vcpkg
      run: |
        vcpkg install imgui[glfw-binding,opengl3-binding]:x64-osx

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: minesweeper-macos
        path: build/Minesweeper
        retention-days: 7

  # Summary job to check if all builds succeeded
  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    if: always()

    steps:
    - name: Check build results
      run: |
        echo "Linux build: ${{ needs.build-linux.result }}"
        echo "Windows build: ${{ needs.build-windows.result }}"
        echo "macOS build: ${{ needs.build-macos.result }}"

        if [ "${{ needs.build-linux.result }}" != "success" ] || \
           [ "${{ needs.build-windows.result }}" != "success" ] || \
           [ "${{ needs.build-macos.result }}" != "success" ]; then
          echo "❌ One or more builds failed"
          exit 1
        else
          echo "✅ All builds succeeded!"
        fi
