name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install dependencies
          run: |
            sudo apt update
            sudo apt install -y build-essential cmake libglfw3-dev libglew-dev libimgui-dev libgtest-dev

        - name: Compile Google Test
          run: |
            cd /usr/src/googletest/googletest
            sudo cmake .
            sudo make
            sudo cp lib/libgtest*.a /usr/lib

        - name: Configure CMake
          run: cmake -B build

        - name: Build and Compile
          run: cmake --build build --target Minesweeper
